Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2022-12, with the labels that each got.

#114 Removing the display order attributes where needed.
  ifrs17/DataModel/DataStructure.ipynb
Labels: enhancement

#124 Fix amortization factor
  ifrs17/Import/ImportScopeCalculation.ipynb
Labels: enhancement

#130 Test runners using ApplicationMessage.Log
  ifrs17-template/Test/AocStructureTest.ipynb
  ifrs17-template/Test/ImportStorageTest.ipynb
  ifrs17-template/Test/MapTemplateAndImportTest.ipynb
  ifrs17-template/Test/ReportStorageTest.ipynb
  ifrs17-template/Test/ReportVariablesTest.ipynb
  ifrs17-template/Test/ReportVariablesTestBase.ipynb
  ifrs17-template/Test/SequenceImportTest.ipynb
  ifrs17-template/Test/TechnicalMarginTest.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Utils/ApplicationMessage.ipynb
Labels: enhancement

#134 Improve documentation
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/ImportScopeCalculation.ipynb
Labels: documentation

#141 versions
  ifrs17/DataModel/DataStructure.ipynb
Labels: enhancement

#144 Remove SnapshotMode from Import Parameters of Initializations NBs
  ifrs17-template/Initialization/InitSystemorphRefDataToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphToDatabase.ipynb
Labels: enhancement

#112 Importer scenario cashflow actuals
  ifrs17-template/Files/Dimensions.csv
  ifrs17-template/Test/Data/ExportIfrsVariable.ipynb
  ifrs17-template/Test/Data/ExportReportVariables.ipynb
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_A.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_APA.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_C.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_DA.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_L.csv
  ifrs17-template/Test/Data/ReportVariableBenchmarks/ReportVariableBenchmarks_2020_12_CH_MTUP10pct_Contractual.csv
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17-template/Test/ImportStorageTest.ipynb
  ifrs17-template/Test/ReportVariablesTest.ipynb
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Export/ExportConfiguration.ipynb
  ifrs17/Import/ImportScopeCalculation.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/EqualityComparers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: enhancement

#145 Consistency
  ifrs17-template/Files/Dimensions.csv
  ifrs17-template/Files/TransactionalData/Actuals_CH_2020_12.csv
  ifrs17-template/Files/TransactionalData/Actuals_CH_2021_3.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2020_12.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2020_12_MTUP10pct.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2021_3.csv
  ifrs17-template/Images/ActualFormat.png
  ifrs17-template/Images/CashflowFormat.png
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/Test/Data/Actuals_CH_2020_12_MTUP10pct.csv
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#150 Openings: remove reimport duplicates
  ifrs17/Import/ImportStorage.ipynb
Labels: bug

#153 Openings: remove reimport duplicates (#150)
  ifrs17/Import/ImportStorage.ipynb
Labels: bug
