Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-08, with the labels that each got.

#363 360 add table name validation
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/Importers.ipynb
Labels: import

#366 fix with explicit names
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/Importers.ipynb
Labels: bug

#365 Fix Loreco in P&L
  ifrs17-template/Files/Dimensions.csv
  ifrs17/Report/ReportScopes.ipynb
Labels: bug

#368 Include the current yield curves
  ifrs17/Report/ParameterReportsQueries.ipynb
Labels: bug, External Stakeholder

#371 Fix to P&L PAA
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/5ImportScope-ToIfrsVar.ipynb
  ifrs17/Report/ReportScopes.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: bug

#367 Tm amount type
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17/Import/4ImportScope-TechnicalMargin.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Test/QueriesScenarioDataTest.ipynb
  ifrs17/Test/TestData.ipynb
Labels: import

#374 369 export to share point
  ifrs17-template/Constants/Sharepoint.ipynb
  ifrs17-template/Export/ExportSettings.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Initialization/ImportSettings.ipynb
  ifrs17-template/Initialization/InitSystemorphBaseToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphRefDataToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphToDatabase.ipynb
  ifrs17-template/Initialization/InitSystemorphToMemory.ipynb
  ifrs17-template/Report/InteractiveReports/Accruals.ipynb
  ifrs17-template/Report/InteractiveReports/Csm-Lc-LoReCo.ipynb
  ifrs17-template/Report/InteractiveReports/Deferrals.ipynb
  ifrs17-template/Report/InteractiveReports/ExperienceAdjustment.ipynb
  ifrs17-template/Report/InteractiveReports/FinancialPerformance.ipynb
  ifrs17-template/Report/InteractiveReports/FulfilmentCashflow.ipynb
  ifrs17-template/Report/InteractiveReports/LIC.ipynb
  ifrs17-template/Report/InteractiveReports/LRC.ipynb
  ifrs17-template/Report/InteractiveReports/LicActuarial.ipynb
  ifrs17-template/Report/InteractiveReports/LoadData.ipynb
  ifrs17-template/Report/InteractiveReports/LrcActuarial.ipynb
  ifrs17-template/Report/InteractiveReports/PresentValue.ipynb
  ifrs17-template/Report/InteractiveReports/RiskAdjustment.ipynb
  ifrs17-template/Report/InteractiveReports/TechnicalMargin.ipynb
  ifrs17-template/Report/InteractiveReports/WrittenActual.ipynb
  ifrs17/Constants/Validations.ipynb
Labels: export

#377 GetHierarchy getter
  ifrs17/Import/ImportStorage.ipynb
Labels: enhancement

#378 changes to FP
  ifrs17/Report/ReportScopes.ipynb
Labels: bug
