Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-02, with the labels that each got.

#202 Reporting scenarios
  ifrs17-template/Test/Data/ExportReportVariables.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Report/ReportConfigurationAndUtils.ipynb
  ifrs17/Report/ReportMutableScopes.ipynb
  ifrs17/Report/ReportStorage.ipynb
Labels: report, scenario

#193 138 migration
  ifrs17-template/Database/Configure.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/Initial.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/MigrationFlow.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/ReadMe.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/Scaffold.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/Snapshot.ipynb
Labels: enhancement

#212 Replace GetElementOrDefault with GetValidElement
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/ImportScopeCalculation.ipynb
  ifrs17/Utils/ApplicationMessage.ipynb
  ifrs17/Utils/Extensions.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#221 Clean up in Reports Notebook
  ifrs17-template/Report/Reports.ipynb
Labels: enhancement

#215 Import With Define Format Fix For With Target Option
  ifrs17-template/Test/MapTemplateAndImportTest.ipynb
  ifrs17-template/Test/ReimportWithDifferentScopeTest.ipynb
  ifrs17-template/Test/SequenceImportTest.ipynb
  ifrs17/Import/Importers.ipynb
Labels: bug

#214 Hot fix loreco
  ifrs17/Import/ImportScopeCalculation.ipynb
  ifrs17/Test/TechnicalMarginTest.ipynb
Labels: bug
