Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-01, with the labels that each got.

#131 Yield curve with main tab and format
  PresentValueSeries/CF_CH_2021_12.xlsx
  PresentValueSeries/CF_DE_2021_12.xlsx
  PresentValueSeries/CF_DE_2022_12.xlsx
  PresentValueSeries/Cashflows.xlsx
  ifrs17-template/Files/Parameters/YieldCurve.csv
  ifrs17-template/Files/Parameters/YieldCurve_2019_12.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_1.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_12.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_3.csv
  ifrs17-template/Files/Parameters/YieldCurve_2021_12.csv
  ifrs17-template/Files/Parameters/YieldCurve_2021_3.csv
  ifrs17-template/Files/Parameters/YieldCurve_2021_6.csv
  ifrs17-template/Initialization/InitSystemorphRefDataToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphToDatabase.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Test/EqualityComparerTest.ipynb
  ifrs17/Test/Tests.ipynb
  ifrs17/Utils/EqualityComparers.ipynb
Labels: enhancement

#162 Test csm switch practical case
  ifrs17-template/Images/CsmLc.png
  ifrs17-template/Images/Switch.png
  ifrs17-template/PracticalUseCases/SingleVsMultipleCsmSwitch/CsmSwitchReports.ipynb
  ifrs17-template/Test/PracticalCasesTest.ipynb
  ifrs17-template/Test/Tests.ipynb
Labels: enhancement

#164 Improving present value documentation
  PresentValueSeries/AnalysisOfChange.png
  PresentValueSeries/Dimensions.xlsx
  PresentValueSeries/PresentValue - Episode 2.ipynb
  PresentValueSeries/PresentValue - Episode 3.ipynb
Labels: documentation

#154 Yield curve Name into Queries
  ifrs17-template/Test/ImportStorageTest.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: enhancement

#163 Parameters report
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17/CalculationEngine.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
Labels: enhancement

#168 Documentation Yield curve change
  ifrs17/DataModel/DataStructure.ipynb
Labels: documentation

#171 Materialize filter condition before the call to CommitToAsync()
  PresentValueSeries/InitializeData.ipynb
  PresentValueSeries/PresentValue - Episode 2.ipynb
  PresentValueSeries/PresentValue - Episode 3.ipynb
  ifrs17/Import/Importers.ipynb
Labels: bug

#175 Clean up
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
Labels: bug

#181 Export scenario column
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Test/MapTemplateAndImportTest.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Export/ExportConfiguration.ipynb
Labels: bug

#182 Async in method name
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
Labels: enhancement

#180 Add InvalidDataNodeForOpening error
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#178 167 activity log v2
  PresentValueSeries/InitializeData.ipynb
  PresentValueSeries/PresentValue - Episode 2.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/Initialization/InitSystemorphBaseToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphRefDataToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphToDatabase.ipynb
  ifrs17-template/Initialization/InitSystemorphToMemory.ipynb
  ifrs17-template/PracticalUseCases/ActualsOutsideThePeriod/ActualsUseCaseDataImport.ipynb
  ifrs17-template/PracticalUseCases/SingleVsMultipleCsmSwitch/CsmSwitchDataImport.ipynb
  ifrs17-template/Test/Data/InitSystemorphToMemoryForTesting.ipynb
  ifrs17-template/Test/MapTemplateAndImportTest.ipynb
  ifrs17-template/Test/SequenceImportTest.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Utils/ActivityLog.ipynb
Labels: enhancement

#185 Remove aggregation at Novelty level in reports
  ifrs17/Report/ReportConfigurationAndUtils.ipynb
Labels: report

#188 Correcting a number of typos
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Utils/ActivityLog.ipynb
Labels: documentation

#161 Yield curve import triggers calculations
  PresentValueSeries/PresentValue - Episode 2.ipynb
  PresentValueSeries/PresentValue - Episode 3.ipynb
  ifrs17-template/Files/Parameters/YieldCurve_2020_1.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_12.csv
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: enhancement, scenario

#192 Place importFormat string outside of variable in GetSign
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#194 Current YieldCurve query fix on YcName filter
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: bug

#151 Adding mandatory AoC step exception in the filter
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/Extensions.ipynb
Labels: enhancement

#199 Fix opening importer
  ifrs17-template/Test/Data/NominalCashflows_CH_2020_12_DT1.1NoPrem.csv
  ifrs17-template/Test/ReimportWithDifferentScopeTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Import/Importers.ipynb
Labels: bug, import

#203 Improve documentation
  PresentValueSeries/InitializeData.ipynb
  PresentValueSeries/PresentValue - Episode 2.ipynb
  PresentValueSeries/PresentValue - Episode 3.ipynb
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/OverviewIFRS17Template.ipynb
  ifrs17-template/README.md
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
  ifrs17/OverviewCalculationEngine.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
Labels: documentation

#207 Fix pv ep2
  PresentValueSeries/Dimensions.xlsx
Labels: bug

#205 Develop to main
  PresentValueSeries/Dimensions.xlsx
  PresentValueSeries/InitializeData.ipynb
  PresentValueSeries/PresentValue - Episode 2.ipynb
  PresentValueSeries/PresentValue - Episode 3.ipynb
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Files/Parameters/YieldCurve_2020_1.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_12.csv
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/OverviewIFRS17Template.ipynb
  ifrs17-template/README.md
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
  ifrs17-template/Test/Data/NominalCashflows_CH_2020_12_DT1.1NoPrem.csv
  ifrs17-template/Test/ReimportWithDifferentScopeTest.ipynb
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/OverviewCalculationEngine.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Test/ImportStorageTest.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Test/ReportStorageTest.ipynb
  ifrs17/Test/TechnicalMarginTest.ipynb
  ifrs17/Test/TestData.ipynb
  ifrs17/Test/Tests.ipynb
  ifrs17/Utils/Extensions.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: enhancement
