Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-11, with the labels that each got.

#410 Ey cases update
  ifrs17-template/Files/DataNodes/DataNodeParameters_FR_2020_12.csv
  ifrs17-template/Files/DataNodes/DataNodeStates_FR_2020_12.csv
  ifrs17-template/Files/DataNodes/DataNodes_FR.csv
  ifrs17-template/Files/TransactionalData/Actuals_FR_2020_12.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_FR_2020_12.csv
  ifrs17-template/Report/ReportEyCases.ipynb
  ifrs17-template/Test/EY-Ifrs17UseCases.ipynb
Labels: enhancement

#412 Sharepoint adjustment
  ifrs17-template/Constants/Sharepoint.ipynb
  ifrs17-template/Export/ExportSettings.ipynb
  ifrs17-template/Initialization/ImportSettings.ipynb
Labels: enhancement

#411 Improve the efficiency of the tests
  ifrs17-template/Initialization/InitSystemorphToMemory.ipynb
  ifrs17-template/Initialization/InitSystemorphUtils.ipynb
  ifrs17-template/Report/ReportEyCases.ipynb
  ifrs17-template/Test/Data/InitSystemorphToMemoryForTesting.ipynb
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17-template/Test/MapTemplateAndImportTest.ipynb
  ifrs17-template/Test/ReimportTest.ipynb
  ifrs17-template/Test/ReimportWithDifferentScopeTest.ipynb
  ifrs17-template/Test/ReportVariablesTest.ipynb
  ifrs17-template/Test/ReportVariablesTestBase.ipynb
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioParametersImportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17-template/Test/SequenceImportTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Import/Importers.ipynb
Labels: enhancement

#420 Remove the validations from queries
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: bug

#426 Premium allocation
  ifrs17-template/Initialization/InitSystemorphBaseToMemory.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Test/DataNodeParameterTest.ipynb
Labels: bug

#419 Base of Solvency calculation for fpna
  fpna-template/Files/AmountType.ipynb
  fpna-template/Files/Cashflows.ipynb
  fpna-template/Files/RiskDriver.ipynb
  fpna-template/Import/FpnaCloseImportTemplate.ipynb
  fpna-template/Initialization/InitSystemorphToMemory.ipynb
  fpna-template/Report/Earnings.ipynb
  fpna-template/Report/Solvency.ipynb
  fpna-template/Test/CHashFlowerTest.ipynb
  fpna-template/Test/Tests.ipynb
  fpna/Constants/Consts.ipynb
  fpna/Constants/Ifrs17CalculationEngine.ipynb
  fpna/DataModel/DataStructure.ipynb
  fpna/Import/Importers.ipynb
  fpna/Import/Scopes.ipynb
  fpna/Import/Storage.ipynb
  fpna/Report/ReportConfigurationAndUtils.ipynb
  fpna/Solvency.ipynb
  fpna/Utils/ExtentionMethods.ipynb
  fpna/Utils/Queries.ipynb
  ifrs17-template/PracticalUseCases/CompareReinsuranceContracts/Reports.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Report/ReportStorage.ipynb
  ifrs17/Test/AocConfigurationTest.ipynb
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Test/DataNodeParameterTest.ipynb
  ifrs17/Test/ExtensionsTest.ipynb
  ifrs17/Test/ImportStorageTest.ipynb
  ifrs17/Test/QueriesScenarioDataTest.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Test/ReportStorageTest.ipynb
  ifrs17/Test/TechnicalMarginTest.ipynb
  ifrs17/Test/Tests.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: documentation, import

#428 Improve init of fpna
  fpna-template/Report/Earnings.ipynb
  fpna-template/Report/Solvency.ipynb
  fpna/Import/Storage.ipynb
  fpna/Utils/Queries.ipynb
Labels: import

#429 Paa lrc scope refined
  fpna-template/Import/FpnaCloseImportTemplate.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Test/ImportStorageTest.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: import, External Stakeholder
