Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-07, with the labels that each got.

#339 Contract term Followup
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/ImportStorage.ipynb
Labels: import

#341 Explanation of Treatment of CDR in Technical Margin
  ifrs17/Import/4ImportScope-TechnicalMargin.ipynb
Labels: documentation

#294 Transactional Data Reimport Test
  ifrs17-template/Test/ReimportTest.ipynb
  ifrs17-template/Test/Tests.ipynb
Labels: enhancement

#344 Aoc steps improvements
  ifrs17-template/Files/Dimensions.csv
  ifrs17/Constants/Enums.ipynb
  ifrs17/Import/1ImportScope-Identities.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/3ImportScope-Actuals.ipynb
  ifrs17/Import/4ImportScope-TechnicalMargin.ipynb
  ifrs17/Import/5ImportScope-ToIfrsVar.ipynb
  ifrs17/Import/6ImportScope-Compute.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Report/ReportScopes.ipynb
  ifrs17/Test/AocConfigurationTest.ipynb
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Test/TechnicalMarginTest.ipynb
  ifrs17/Test/TestData.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: import

#345 Extend Parsed Variables
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#348 Filter identities to compute import scopes
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12__F.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__F.csv
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17-template/Test/ReimportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/3ImportScope-Actuals.ipynb
  ifrs17/Import/4ImportScope-TechnicalMargin.ipynb
  ifrs17/Import/5ImportScope-ToIfrsVar.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: import

#351 Placeholder for the customer project method
  ifrs17/Import/3ImportScope-Actuals.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#352 Ce for projections
  ifrs17-template/Files/DataNodes/DataNodes_CH.csv
  ifrs17-template/Files/Parameters/YieldCurve_2020_1.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2020_12_Projection.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2021_3_Projection.csv
  ifrs17-template/Test/Data/ExportIfrsVariable.ipynb
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__BE_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__C_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__L_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__RA_Projection_DTP.csv
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17/Import/1ImportScope-Identities.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/3ImportScope-Actuals.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: enhancement

#356 Little things on projections
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2021_3_Projection.csv
  ifrs17-template/Report/ReportProjections.ipynb
  ifrs17-template/Test/Data/ExportIfrsVariable.ipynb
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__BE_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__C_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__L_Projection_DTP.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__RA_Projection_DTP.csv
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/3ImportScope-Actuals.ipynb
Labels: enhancement
