Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-03, with the labels that each got.

#226 Hot fix loreco
  ifrs17/Import/ImportScopeCalculation.ipynb
  ifrs17/Test/TechnicalMarginTest.ipynb
Labels: bug

#227 Update version reference to v1.1.1
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
Labels: documentation

#228 update to v1.1.1
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
Labels: documentation

#232 Fixes scenarios
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17-template/Test/Tests.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Report/ReportMutableScopes.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: scenario

#241 Grouping scenario constants
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17-template/Test/ScenarioYieldCurveImportTest.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Report/ReportMutableScopes.ipynb
  ifrs17/Utils/Extensions.ipynb
Labels: enhancement

#218 new scenario data queries tests
  ifrs17/Report/ReportConfigurationAndUtils.ipynb
  ifrs17/Test/ImportStorageTest.ipynb
  ifrs17/Test/QueriesScenarioDataTest.ipynb
  ifrs17/Test/QueriesTest.ipynb
  ifrs17/Test/TestData.ipynb
  ifrs17/Test/Tests.ipynb
Labels: scenario

#249 Reference v1.2.0 in Template project
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
Labels: documentation
