Repository Systemorph/IFRS17CalculationEngine, pull requests merged in 2023-04, with the labels that each got.

#263 Cumulate nominal
  ifrs17-template/Import/InteractWithImportScopes/EvaluateImportScopes.ipynb
  ifrs17-template/Import/InteractWithImportScopes/Re-evaluateImportScopes.ipynb
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12_MTUP10pct_BE.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12__BE.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2020_12__RA.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__BE.csv
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__RA.csv
  ifrs17/Constants/Consts.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/5ImportScope-ToIfrsVar.ipynb
  ifrs17/Import/6ImportScope-Compute.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Test/Tests.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: import

#269 Cashflow Interpolation New Migration Flow
  ifrs17-template/Database/MigrationAndScaffolding/Initial.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/Snapshot.ipynb
Labels: bug

#197 IfrsVariable Projections
  ifrs17-template/Files/DataNodes/DataNodeStates_CH_2020_12.csv
  ifrs17-template/Files/DataNodes/DataNodes_CH.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2020_12_Projection.csv
  ifrs17-template/Files/TransactionalData/NominalCashflows_CH_2021_3_Projection.csv
  ifrs17-template/Import/InteractWithImportScopes/EvaluateImportScopes.ipynb
  ifrs17-template/Test/Data/IfrsVariableBenchmarks/BM_CH_2021_3__BE_Projection_DTP.csv
  ifrs17-template/Test/IfrsVariablesTest.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/1ImportScope-Identities.ipynb
  ifrs17/Import/2ImportScope-PresentValue.ipynb
  ifrs17/Import/4ImportScope-TechnicalMargin.ipynb
  ifrs17/Import/6ImportScope-Compute.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Report/ParameterReportMutableScopeInteractive.ipynb
  ifrs17/Report/ParameterReportsQueries.ipynb
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Test/EqualityComparerTest.ipynb
  ifrs17/Utils/EqualityComparers.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: projection, import

#267 Allow for more Aoc steps in the Combined section
  ifrs17/Test/AocStructureTest.ipynb
  ifrs17/Utils/ImportCalculationMethods.ipynb
Labels: import

#275 Fix data to export
  ifrs17-template/Report/InteractiveReports/Accruals.ipynb
  ifrs17-template/Report/InteractiveReports/Csm-Lc-LoReCo.ipynb
  ifrs17-template/Report/InteractiveReports/Deferrals.ipynb
  ifrs17-template/Report/InteractiveReports/ExperienceAdjustment.ipynb
  ifrs17-template/Report/InteractiveReports/FinancialPerformance.ipynb
  ifrs17-template/Report/InteractiveReports/FulfilmentCashflow.ipynb
  ifrs17-template/Report/InteractiveReports/LIC.ipynb
  ifrs17-template/Report/InteractiveReports/LRC.ipynb
  ifrs17-template/Report/InteractiveReports/LicActuarial.ipynb
  ifrs17-template/Report/InteractiveReports/LrcActuarial.ipynb
  ifrs17-template/Report/InteractiveReports/RiskAdjustment.ipynb
  ifrs17-template/Report/InteractiveReports/TechnicalMargin.ipynb
  ifrs17-template/Report/InteractiveReports/WrittenActual.ipynb
Labels: report

#273 Refactor ActivityLog DataBase Tables
  ifrs17-template/Database/MigrationAndScaffolding/Initial.ipynb
  ifrs17-template/Database/MigrationAndScaffolding/Snapshot.ipynb
  ifrs17/Utils/ActivityLog.ipynb
Labels: enhancement

#252 Openings scenario
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Test/ImportStorageTest.ipynb
  ifrs17/Test/TestData.ipynb
Labels: bug, scenario

#279 Scenario improvements
  ifrs17-template/Files/TransactionalData/Actuals_CH_2020_12.csv
  ifrs17-template/Test/ScenarioDataImportTest.ipynb
  ifrs17/Constants/Consts.ipynb
  ifrs17/Constants/Validations.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/OverviewCalculationEngine.ipynb
  ifrs17/Test/EqualityComparerTest.ipynb
  ifrs17/Utils/EqualityComparers.ipynb
Labels: bug, enhancement

#283 282 restore filters
  ifrs17/Report/ReportMutableScopesInteractive.ipynb
Labels: bug

#284 Debugging NB
  ifrs17-template/Import/InteractWithImportScopes/EvaluateImportScopes.ipynb
Labels: import

#285 Bug Fix for GetAllArgsAsync
  ifrs17/Import/Importers.ipynb
  ifrs17/Report/ReportStorage.ipynb
Labels: bug

#280 Scenario documentation
  ifrs17-template/Report/Reports.ipynb
  ifrs17/DataModel/DataStructure.ipynb
  ifrs17/Import/ImportStorage.ipynb
  ifrs17/Import/Importers.ipynb
  ifrs17/Utils/Queries.ipynb
Labels: documentation, scenario

#289 Documentation
  ifrs17-template/Constants/CalculationEngine.ipynb
  ifrs17-template/Export/MapTemplate.ipynb
  ifrs17-template/Import/CloseImportTemplate.ipynb
  ifrs17-template/InputFormatDescription.ipynb
  ifrs17-template/Report/ParameterReports.ipynb
  ifrs17-template/Report/Reports.ipynb
  ifrs17/Report/ReportStorage.ipynb
Labels: documentation
